### ISSUE TITLE
Hi hello module does not work

### ISSUE THREAD

**Issue by grkmcngns** [Xposed-Modules-Repo/com.gswxxn.camerasnap#2]
![Screenshot_2023-05-18-18-23-37-898_com miui securitycenter](https://github.com/Xposed-Modules-Repo/com.gswxxn.camerasnap/assets/133990712/1413b204-bffe-41e0-bfcc-82d332647b10)
![Screenshot_2023-05-18-18-23-50-760_com android settings](https://github.com/Xposed-Modules-Repo/com.gswxxn.camerasnap/assets/133990712/f81bf394-ddb8-4e13-b96b-fae0f5ed2778)
![Screenshot_2023-05-18-18-00-19-751_com android camera](https://github.com/Xposed-Modules-Repo/com.gswxxn.camerasnap/assets/133990712/636903a1-99e0-4afe-ad8a-5b984077f5d2)
Module Active But Keys Unresponsive No Video Or Photo Recording

**Comment by GSWXXN** [comment]
Try to check `System Framework` in the LSPosed module scope, although it is not in the recommended apps list. And then reboot your phone

If the problem still exists, please provide the LSPosed log
